# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b358df17da4e91a357768ef9f42d46dd744bd0d1726339c292737388e7942b8b92e540e4e551882314d19851bb2c4eab397c06062106bbc65b5efbdc66998087

test:
  secret_key_base: b4a72164ec3468b911ae8b49808f850956908e846807ffa561b83cdb849ec75454cb0a3b125386fb4cc8c8da477a8ae0b120254385520210417b3f5cc03fe146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
